openapi: 3.2.0
info:
  title: Spekit Spek Views API
  version: 1.0.0 (v1)
  description: Here, you will find comprehensive information and resources for integrating and utilizing our powerful API services.
  license:
    name: License Agreement
    url: https://spekit.com/api-license-agreement
tags:
- name: Spek Views
paths:
  /v1/analytics/speks/views/:
    get:
      operationId: v1_analytics_speks_views_list
      description: Returns a list of all views made on speks, including the user details, spek details, and the views itself.
      summary: List all spek views
      parameters:
      - name: cursor
        required: false
        in: query
        description: The pagination cursor value.  This is an opaque key provided in the 'next' and 'previous' URLs in API responses. It may be ignored, otherwise.
        schema:
          type: string
      - in: query
        name: end_date
        schema:
          type: string
          format: date-time
        description: End Date till then we need to filter the results.
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page. Default value is 50. Maximum is 100.
        schema:
          type: integer
      - in: query
        name: start_date
        schema:
          type: string
          format: date-time
        description: Start Date from where we need to start filtering.
      tags:
      - Spek Views
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedSpekViewsList'
          description: ''
components:
  schemas:
    TeamRole:
      type: object
      description: Teams and roles of a user.
      properties:
        team:
          type: string
          readOnly: true
        role:
          type: string
          readOnly: true
      required:
      - role
      - team
    SpekDetails:
      type: object
      properties:
        id:
          type: string
        link:
          type: string
        type_short:
          type: string
        label:
          type: string
        deleted:
          type: boolean
      required:
      - deleted
      - id
      - label
      - link
      - type_short
    PaginatedSpekViewsList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
        previous:
          type:
          - string
          - 'null'
        results:
          type: array
          items:
            $ref: '#/components/schemas/SpekViews'
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
          maxLength: 254
        is_active:
          type: boolean
        created_on:
          type: string
          format: date-time
        teams:
          type: array
          items:
            $ref: '#/components/schemas/TeamRole'
      required:
      - email
      - first_name
      - teams
    SpekViews:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        spek:
          allOf:
          - $ref: '#/components/schemas/SpekDetails'
          readOnly: true
        view:
          allOf:
          - $ref: '#/components/schemas/TermViews'
          readOnly: true
        associated_teams:
          type: array
          items:
            type: string
      required:
      - associated_teams
      - spek
      - user
      - view
    TermViews:
      type: object
      properties:
        id:
          type: string
        source:
          type: string
        user_action:
          type: string
        created_on:
          type: string
          format: date-time
      required:
      - id
      - source
      - user_action
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
