openapi: 3.2.0
info:
  title: Spekit User Activities API
  version: 1.0.0 (v1)
  description: Here, you will find comprehensive information and resources for integrating and utilizing our powerful API services.
  license:
    name: License Agreement
    url: https://spekit.com/api-license-agreement
tags:
- name: User Activities
paths:
  /v1/analytics/user-activities/:
    get:
      operationId: v1_analytics_user_activities_list
      description: 'Returns a list of all users who performed the mentioned activity on the Spekit platform.


        Supported activity types and their corresponding data structures:


        1. topic_created:

        - id: string

        - name: string

        - description: string


        2. search:

        - search_id: string

        - keywords: string

        - source: string

        - search_api: string


        3. team_created:

        - id: string

        - name: string

        - description: string


        4. files_uploaded/marked_asset_read:

        - id: string

        - file_name: string

        - label: string

        - file_store_id: string

        - category: string

        - file_size: number

        - url: string

        - content_type: string

        - shareable: boolean


        5. asset view:

        - view_id: string

        - content_id: string

        - content_name: string

        - content_type: string

        - content_source: string

        - content_link: string

        - view_source: string

        - external_view: boolean


        6. reaction:

        - reaction_id: string

        - reaction: string

        - spek_id: string

        - spek_name: string

        - spek_type: string

        - spek_url: string


        7. spek_created/marked_spek_read:

        - spek_id: string

        - spek_type: string

        - spek_name: string

        - spek_url: string

        - deleted: boolean

        - age: number

        - expert_user_id: string

        - expert_name: string

        - is_shareable: boolean


        8. spek view:

        - view_id: string

        - spek_id: string

        - spek_type: string

        - spek_name: string

        - spek_url: string

        - view_source: string


        9. flow_start/flow_completion/flow_created:

        - id: string

        - label: string

        - start_on: datetime

        - end_on: datetime

        - deleted: boolean

        - status: string

        - frequency_period: string

        - frequency_value: number

        - autolaunch: boolean


        10. spotlight_created/spotlight_completion:

        - id: string

        - label: string

        - start_on: datetime

        - end_on: datetime

        - deleted: boolean

        - status: string

        - frequency_period: string

        - frequency_value: number

        - autolaunch: boolean


        11. knowledge_check_created:

        - id: string

        - title: string

        - starts_on: datetime

        - ends_on: datetime

        - passing_score: number

        - status: string

        - message: string

        - resource: string


        12. knowledge_check_attempt:

        - knowledge_check_id: string

        - pct_correct: number

        - total_questions_correct: number

        - total_questions_attempted: number

        - passed: boolean

        - completed_at: datetime

        - status: string


        13. knowledge_check_question_attempt:

        - question_id: string

        - question_title: string

        - is_correct: boolean

        - knowledge_check_id: string


        14. recommendation:

        - id: string

        - label: string

        - source: string

        - version: string

        - metric: string

        - screen_name: string

        - url: string

        - recommendation_type: string

        - score: number

        - engine: string

        - question: string

        - response: string

        - follow_up_question: string

        - user_message: string

        - ai_response: string

        - query: string

        - sources: string

        - is_rex_active: boolean

        - app: string


        15. api_auth_token_generated/api_auth_token_revoked:

        - id: string

        - key: string

        - expiry: string

        - expiry_dt: datetime

        - description: string

        - deleted: boolean'
      summary: List all users for Activity type
      parameters:
      - in: query
        name: activity_type
        schema:
          type: string
          enum:
          - api_auth_token_generated
          - api_auth_token_revoked
          - asset view
          - files_uploaded
          - flow_completion
          - flow_created
          - flow_start
          - knowledge_check_attempt
          - knowledge_check_created
          - knowledge_check_question_attempt
          - marked_asset_read
          - marked_spek_read
          - reaction
          - recommendation
          - search
          - spek view
          - spek_created
          - spotlight_completion
          - spotlight_created
          - team_created
          - topic_created
        description: Filter by activity type. Returns all activities if not specified.
      - name: cursor
        required: false
        in: query
        description: The pagination cursor value.  This is an opaque key provided in the 'next' and 'previous' URLs in API responses. It may be ignored, otherwise.
        schema:
          type: string
      - in: query
        name: end_date
        schema:
          type: string
          format: date-time
        description: End Date till then we need to filter the results.
      - name: page_size
        required: false
        in: query
        description: Number of results to return per page. Default value is 50. Maximum is 100.
        schema:
          type: integer
      - in: query
        name: start_date
        schema:
          type: string
          format: date-time
        description: Start Date from where we need to start filtering.
      tags:
      - User Activities
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUserActivityList'
          description: ''
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
          maxLength: 254
        is_active:
          type: boolean
        created_on:
          type: string
          format: date-time
        teams:
          type: array
          items:
            $ref: '#/components/schemas/TeamRole'
      required:
      - email
      - first_name
      - teams
    UserActivity:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        created_on:
          type: string
          format: date-time
        activity_type:
          type: string
        activity_id:
          type: string
        ip:
          type: string
      required:
      - activity_id
      - activity_type
      - ip
      - user
    PaginatedUserActivityList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type:
          - string
          - 'null'
        previous:
          type:
          - string
          - 'null'
        results:
          type: array
          items:
            $ref: '#/components/schemas/UserActivity'
    TeamRole:
      type: object
      description: Teams and roles of a user.
      properties:
        team:
          type: string
          readOnly: true
        role:
          type: string
          readOnly: true
      required:
      - role
      - team
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
